name: HARQIS-DEMO Test Flow
# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [ trigger-harqis-demo-test ]

jobs:
  run-demo-and-test:
    runs-on: ubuntu-latests
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Build Docker image without using cache
      run: docker build --no-cache -t harqis-demo .

    - name: Run tests
      run: docker run -m harqis-demo
      env:
        ENV_ROOT_DIRECTORY: /app