name: HARQIS-DEMO Execute Setup Flow
# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [ trigger-harqis-demo-test ]

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Set Up Git Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build  --target tests --no-cache -t harqis-pytest .

    - name: Start Services
      run: docker-compose up &

    - name: Run Tests
      run: docker run harqis-pytest
      env:
        ENV_ROOT_DIRECTORY: /app

  run-behave:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Git Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build  --target behave --no-cache -t harqis-behave .

      - name: Start Services
        run: docker-compose up &

      - name: Run Tests
        run: docker run harqis-behave
        env:
          ENV_ROOT_DIRECTORY: /app



