name: HARQIS-DEMO Test Flow
# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-demo-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: List files
      run: ls

    - name: Diagnose filesystem state
      run: |
        pwd
        ls -lah
        echo $PYTHONPATH
        ls -lah venv/lib


    - name: Run get_started script
      run: python get_started.py

    - name: Run pytest
      run: pytest

